name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe it below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New MCP Tool
        - Enhancement to Existing Tool
        - Database/Storage Improvement
        - Performance Optimization
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: tool-category
    attributes:
      label: Tool Category (if applicable)
      description: Which category would this feature relate to?
      options:
        - Infrastructure Tools
        - Database Tools
        - Memory Tools
        - Interaction Tools
        - Cognitive Tools
        - New Category
        - Not Applicable

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a concrete use case for this feature
      placeholder: |
        As a [role], I want to [action] so that [benefit].

        Example: As a developer, I want to batch import interactions so that I can migrate from another system.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions you've considered
      placeholder: I considered using... but...

  - type: textarea
    id: example
    attributes:
      label: Example Implementation
      description: If you have ideas on how this could be implemented, share them here
      render: typescript
      placeholder: |
        // Example API:
        await newTool({
          param1: "value",
          param2: 123
        });

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Project cannot proceed without it
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute?
      options:
        - label: I'd be willing to implement this feature
        - label: I'd be willing to test this feature
        - label: I can provide additional use cases/feedback

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: Links to similar features in other tools, mockups, etc.
