name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Run tests
              run: bun test

            - name: Type check
              run: bun run typecheck

            - name: Build
              run: bun run build

            - name: Check build size
              run: |
                  BUILD_SIZE=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js)
                  BUILD_SIZE_MB=$((BUILD_SIZE / 1024 / 1024))
                  echo "Build size: ${BUILD_SIZE_MB}MB"
                  if [ $BUILD_SIZE_MB -gt 5 ]; then
                    echo "::warning::Build size (${BUILD_SIZE_MB}MB) exceeds 5MB threshold"
                  fi
