name: Release

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            version:
                description: "Version to release (e.g., v1.0.0)"
                required: false

permissions:
    contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Run tests
              run: bun test

            - name: Type check
              run: bun run typecheck

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get version from package.json
              id: package-version
              run: echo "version=v$(jq -r .version package.json)" >> $GITHUB_OUTPUT

            - name: Check if tag exists
              id: check-tag
              run: |
                  if git ls-remote --tags origin | grep -q "refs/tags/${{ steps.package-version.outputs.version }}"; then
                    echo "exists=true" >> $GITHUB_OUTPUT
                  else
                    echo "exists=false" >> $GITHUB_OUTPUT
                  fi

            - name: Download build artifact
              if: steps.check-tag.outputs.exists == 'false'
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist/

            - name: Create tarball
              if: steps.check-tag.outputs.exists == 'false'
              run: |
                  tar -czf skynet-${{ steps.package-version.outputs.version }}.tar.gz \
                    dist/ \
                    package.json \
                    bun.lock \
                    README.md \
                    LICENSE \
                    docker-compose.yml

            - name: Create Release
              if: steps.check-tag.outputs.exists == 'false'
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.package-version.outputs.version }}
                  name: Release ${{ steps.package-version.outputs.version }}
                  files: |
                      skynet-${{ steps.package-version.outputs.version }}.tar.gz
                      dist/index.js
                  generate_release_notes: true
                  draft: false
                  prerelease: ${{ contains(steps.package-version.outputs.version, 'alpha') || contains(steps.package-version.outputs.version, 'beta') || contains(steps.package-version.outputs.version, 'rc') }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
