name: Release

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:
        inputs:
            version:
                description: "Version to release (e.g., v1.0.0)"
                required: true

permissions:
    contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Run tests
              run: bun test

            - name: Type check
              run: bun run typecheck

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist/

            - name: Create tarball
              run: |
                  tar -czf skynet-mcp-${{ github.ref_name }}.tar.gz \
                    dist/ \
                    package.json \
                    bun.lock \
                    README.md \
                    LICENSE \
                    docker-compose.yml

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      skynet-mcp-${{ github.ref_name }}.tar.gz
                      dist/index.js
                  generate_release_notes: true
                  draft: false
                  prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
